services:

  postgres:
    container_name: diary_server_db
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}

  liquibase:
    image: liquibase/liquibase:4.1
    command:
      - --changeLogFile=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://diary_server_db:5432/${POSTGRES_DB}
      - --username=${POSTGRES_USER}
      - --password=${POSTGRES_PASSWORD}
      - update
    depends_on:
      - postgres
    volumes:
      - ./migration:/liquibase/changelog

volumes:
  pgdata: { }
